defmodule Mapper do
  # send process id of current `Map` process to the partition process - this will enable us to check whether out Map processes are still running later on in Partition.  After that, we use Enum.each to send individual words from the list generated by splitting each line based on the space char to the `Partition` process
  def map(line, partition_process_id) do
    send(partition_process_id, {:process_put, self()})

    Enum.each(String.split(line, " "), fn key -> send(partition_process_id, {:value_put, key}) end)
  end
end
